[theme]
primaryColor="#2d31bd"
backgroundColor="#1a1a19"
secondaryBackgroundColor="#142314"
textColor="#27ad8a"
font="serif"
[css]
source = '''
@media (max-width: 50px) {
    body {
        /* Adjust styles for smaller screens */
        background-color: #1a1a19;
        color: #27ad8a;
    }
}
'''
